export const TOKEN_KEY = 'accessToken'
export const REFRESH_KEY = 'refreshToken'
export const TOKEN_KEY2 = 'access-token'
export const REFRESH_KEY2 = 'refresh-token'
export const NICK_NAME = 'nickName'
export const EMAIL = 'email'
export const USER_ID = 'userId'
